apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ysk-d/kubernetes-native-testbed.git
    targetRevision: develop
    path: manifests/infra/argocd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

