apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ysk-d/kubernetes-native-testbed.git
    targetRevision: develop
    path: manifests/infra/loki
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

